P2-2272 to add CreatedDate to ProviderCourse for comparison with RAT …
SkillsFundingAgency/das-roatp-api pull request #164
Opened 2024-10-31 11:42 UTC by alandburns

…requests

2024-11-07 17:34 UTC, ChrisJWoodcock requested changes

2024-11-07 17:34 UTC, ChrisJWoodcock commented on src/SFA.DAS.Roatp.Database/Tables/ProviderCourse.sql
> +    [CreatedDate] DATETIME2 DEFAULT GETUTCDATE(),
You haven't specified is this is nullable, unspecified it would be nullable but you have given it a default so it will be created and populated with GETUTCDATE(), if a default is used then usually this is because it is non-nullable

2024-11-07 17:34 UTC, ChrisJWoodcock commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/P2-2272.sql
> +		  ,ROW_NUMBER() OVER (PARTITION BY prv.[Id], JSON_VALUE([initialState],'$.LarsCode')ORDER BY [AuditDate] DESC) Seqn
This is joining from the audit to the provider courses so finding any provider courses which have an audit record and updating those - which is as per the description

2024-11-07 17:34 UTC, ChrisJWoodcock commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/P2-2272.sql
> +UPDATE [dbo].[ProviderCourse]
This is attempting to set those record which did not have an audit value to the day before first audit value (presumably because auditing started after some rows where added), however since the column is being added (see comment below) with a default of GETUTCDATE() there will not be any null CreatedDate values

2024-11-08 09:54 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/P2-2272.sql
> +UPDATE [dbo].[ProviderCourse]
No that is not how it works.
Adding a nullable column with a default value does not add the default value.
This is exactly what I want this to do.

2024-11-08 11:35 UTC, ChrisJWoodcock commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/P2-2272.sql
> +UPDATE [dbo].[ProviderCourse]
That is really interesting - confirmed experimentally - as I would not of thought that to be the case

2024-11-08 11:35 UTC, ChrisJWoodcock approved these changes

2024-11-26 12:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Script.PostDeployment.sql
> +:r .\PostDeploymentScripts\P2-2272.sql
Can the script not be in PostDeployment as it will slow down deployment heavily.
We just need to patch the data once post deployment as any new records will update the date automatically
.
I suggest that the script should be executed ad-hocly to avoid re-running it every time as part of deployment.

2024-11-26 14:38 UTC, ChrisJWoodcock commented on src/SFA.DAS.Roatp.Database/Script.PostDeployment.sql
> +:r .\PostDeploymentScripts\P2-2272.sql
The script has been removed and will be run in PROD after the deployment

2024-11-26 16:26 UTC, merged