CSP-1830_Managing_Standards_(RoATPv2)_database_changes_for_FAT_2025
SkillsFundingAgency/das-roatp-api pull request #165
Opened 2024-12-16 10:04 UTC by alandburns

2024-12-16 10:25 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Database/Tables/ProviderEmployerStars.sql
> +﻿CREATE TABLE [dbo].[ProviderEmployerStars]
table does not match the spec of the story

2024-12-16 10:26 UTC, MarkFCain reviewed
ProviderEmployerStars does not match spec, otherwise all good

2024-12-16 10:27 UTC, DevenKShah requested changes

2024-12-16 10:27 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Script.PostDeployment.sql
> +:r .\PostDeploymentScripts\CSP-1832-Insert_ProviderEmployerStars.sql
Remove this from POST Deployment as it will run each time we deploy, create a `Scripts` folder in the database project and move the files there. We will run this ad-hocly in each environment.

2024-12-16 10:27 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/ProviderEmployerStars.sql
> +	[Id] INT NOT NULL PRIMARY KEY
Are we missing more columns here?

2024-12-16 10:27 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/CSP-1831-Insert_NationalQAR.sql
If you are planning to add the scripts in a later story, should have just created these later as well, do not see a point of adding empty files

2024-12-16 10:27 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/ProviderApprenticeStars.sql
> +    [TimePeriod] NVARCHAR(50) NOT NULL
TimePeriod else where is varchar(4) why is it different here?

2024-12-16 10:36 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Script.PostDeployment.sql
> +:r .\PostDeploymentScripts\CSP-1832-Insert_ProviderEmployerStars.sql
That is exactly the point of having post-deployment script, to ensure that the data is correct when first needed.
The post-deployment scripts are self regulating, so they will only run once in any environment.
And when the load JOB is eventually successfully deployed to PROD they can be removed from the build.

2024-12-16 10:55 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Tables/ProviderEmployerStars.sql
> +	[Id] INT NOT NULL PRIMARY KEY
Looks like I didn't copy across the spec.

2024-12-16 10:56 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Tables/ProviderApprenticeStars.sql
> +    [TimePeriod] NVARCHAR(50) NOT NULL
QAR hold its data as "2223"
Feedback holds its data as "AY2324"
This retains the origins of the data.

2024-12-16 10:57 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/PostDeploymentScripts/CSP-1831-Insert_NationalQAR.sql
Should not be empty.
I will check

2024-12-16 11:16 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Script.PostDeployment.sql
> +:r .\PostDeploymentScripts\CSP-1832-Insert_ProviderEmployerStars.sql
However, I have now included as manual scripts

2024-12-16 11:17 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Tables/ProviderApprenticeStars.sql
> +    [TimePeriod] NVARCHAR(50) NOT NULL
Mind-you it should be 6 not 50!!

2024-12-16 11:19 UTC, alandburns commented on src/SFA.DAS.Roatp.Database/Tables/ProviderApprenticeStars.sql
> +    [TimePeriod] NVARCHAR(50) NOT NULL
The original data has NVARCHAR(50) in Apprentice Feedback and Employer Feedback databases.

2024-12-16 15:06 UTC, DevenKShah approved these changes
I prefer we remove any scripts/tables that we do not need at the moment.

2025-01-08 15:42 UTC, MarkFCain approved these changes

2025-01-10 14:20 UTC, merged