CSP-66-inner-ProvideCourseLocations
SkillsFundingAgency/das-roatp-api pull request #32
Opened 2022-05-20 07:57 UTC by raviudari01

2022-05-22 20:01 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Api/Controllers/ProviderCourseLocationsController.cs
> +        [Route("/providerCourseLocations/{providerCourseId}")]
End point route is incorrect. Please read this document https://skillsfundingagency.atlassian.net/wiki/spaces/NDL/pages/3716841559/Implementation+notes#Endpoint-mapping

2022-05-26 06:20 UTC, DevenKShah requested changes
The route is wrong again.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryHandler.cs
> +            if (!providerCourseLocations.Any())
We should return an empty list here.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryHandler.cs
> +                _logger.LogInformation("Provider data not found for {ukprn} and {larsCode}", request.Ukprn, request.LarsCode);
This check is already done in the validator, so need to check again here.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryHandler.cs
> +                _logger.LogInformation("Provider Course data not found for {ukprn} and {larsCode}", request.Ukprn, request.LarsCode);
I have recommended adding validation for LarsCode in the validator. Any further validation is not necessary here. If there is no data for the combination of Ukprn ad LarsCode then we should just return an empty collection. 

We just need one call to the repository here, use the Ukprn and Larscode to deep filter from ProviderCourseLocation.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidator.cs
> +            RuleFor(x => x.Ukprn)
Validation is missing for the larscode. A async validation for the larscode against Standards should be done as well.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Data/Configuration/RegionConfiguration.cs
> +        {
This configuration is redundant as far as I can see.

2022-05-26 06:20 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidatorTests.cs
> +        public async Task Validate_AcceptsEightDigitNumbersOnly(int ukprn, int providerCourseId, bool expectedResult)
DRY. 
This is a full copy of existing tests. Ukprn and LarcCode will be mostly be there in all the queries and commands. We need to start thinking of a way to not repeat validators for these fields and  hence not repeat these tests either.

2022-05-26 16:33 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Api/Controllers/ProviderCourseLocationsController.cs
> +    [Route("[controller]")]
It is redundant as you are specifying the route on the action.

2022-05-26 16:39 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Queries/ProviderCourseLocationModel.cs
> +                LocationName = source.Location?.LocationName,
If I am reading this without any knowledge, it would seem to me that the Location can be null, which then raises other questions. You code intent should be clear. A unnecessary null check would create confusion.

2022-05-27 06:45 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Api.UnitTests/Controllers/ProviderCourseLocationsControllerTests.cs
> +
remove space

2022-05-27 06:56 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationModelTest.cs
> +            var model = (ProviderCourseLocation)location;
This test is just checking a providerCourseLocation maps to a providerCourseLocation.

I think this should be:
 ProviderCourseLocationModel model = location;

or

var model = (ProviderCourseLocationModel)location;

2022-05-27 07:02 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidatorTests.cs
> +        public async Task Validate_ExecutesAsyncValidatorForInvalidUkprnLarsCode()
simplify title: Validate_InvalidUkprnLarsCode

2022-05-27 07:03 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidatorTests.cs
> +        public async Task Validate_ExecutesAsyncValidatorForValidUkprnLarsCode_ReturnProviderCourseDataNotFound()
simplify title: Validate_InvalidUkprnLarsCode_CourseDataNotFound()

2022-05-27 07:05 UTC, MarkFCain reviewed
mostly minor comments, please fix the test for 'ProviderCourseLocationModelTest'

2022-05-27 07:10 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidatorTests.cs
> +        public async Task Validate_AcceptsEightDigitNumbersOnly(int ukprn, int providerCourseId, bool expectedResult)
You cant just delete the tests. My suggestion was to refactor so that we don't have to repeat tests.

2022-05-30 07:10 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Queries/ProviderCourseLocationsQueryValidatorTests.cs
> +            Assert.AreEqual(expectedErrorMessage2, result.Errors[1].ErrorMessage);
This is minor and at your discretion, but I prefer tests to sets of details not to be bound to a specific index.
Is this kind of approach possible: Assert.IsTrue(results.Errors.Contains(expectedErrorMessage1)

If it takes more than a few minutes to change, please leave it as is.

2022-05-30 07:12 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Database/Tables/ProviderCourseLocation.sql
> -    [OffersPortableFlexiJob] BIT NULL,
Taking this out here will cause build problems, I'm under the impression we're saving all the changes that remove fields for their own story. If you have discussed with Deven, then fine, otherwise we need to be careful when we remove fields from the current tables.

2022-05-30 07:12 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Domain/Entities/ProviderCourseLocation.cs
> -        public bool? OffersPortableFlexiJob { get; set; }
re the comment above, it's fine to remove the field here

2022-05-30 07:13 UTC, MarkFCain approved these changes
approved,minor comment in a test, and issue with database field being removed

2022-05-30 08:32 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Database/Tables/ProviderCourseLocation.sql
> -    [OffersPortableFlexiJob] BIT NULL,
Agree it was discussed, but removing fields breaks the build.  We usually have to delete a table entirely from each release environment to fix that, so this takes some coordination, so we don't do it routinely.

2022-05-31 06:56 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/ProviderCourseLocation.sql
> -    [OffersPortableFlexiJob] BIT NULL,
@raviudari01 it was agreed to not return the field in the response. But we didn't talk about database changes. As @MarkFCain explained this causes build issues. There are other database changes required and we will consider removing the field as part of that task.

2022-05-31 09:33 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Domain/Entities/ProviderCourseLocation.cs
> +        public bool? OffersPortableFlexiJob { get; set; }
This can be removed from the entity (but leave it in the database)

2022-06-13 09:24 UTC, merged