CSP-105-inner-ConfirmRegulatedStandard
SkillsFundingAgency/das-roatp-api pull request #43
Opened 2022-06-09 13:41 UTC by raviudari01

2022-06-13 06:53 UTC, DevenKShah requested changes
This PR is showing 62 files changed is this correct?

2022-06-14 20:04 UTC, DevenKShah requested changes

2022-06-14 20:04 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Api/Controllers/ProviderCourseEditController.cs
> +        public async Task<IActionResult> Save([FromRoute] int ukprn, [FromRoute] int larsCode, ProviderCourseEditConfirmRegulatedStandardModel model)
We have agreed to extend existing endpoint for any edits on ProviderCourse. Remove this new endpoint and use the existing one.

2022-06-15 07:43 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application/ProviderCourse/Commands/UpdateApprovedByRegulator/UpdateApprovedByRegulatorCommandHandler.cs
> +            _logger.LogInformation("Update confirm regulated standard for ukprn: {ukprn} LarsCode: {larscode}", request.Ukprn, request.LarsCode);
optional: change 'confirm regulated' to 'approved by regulator'

2022-06-15 07:45 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application/ProviderCourse/Commands/UpdateApprovedByRegulator/UpdateApprovedByRegulatorCommandValidator.cs
> +    public class UpdateApprovedByRegulatorCommandValidator : AbstractValidator<UpdateApprovedByRegulatorCommand>
add test coverage for this validator please

2022-06-15 07:46 UTC, MarkFCain reviewed
minor comments and coverage needed on validator

2022-06-15 15:32 UTC, DevenKShah approved these changes
Project file needs reverting.

2022-06-15 15:32 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/SFA.DAS.Roatp.Application.UnitTests.csproj
> +  <ItemGroup>
Remove this

2022-06-17 09:02 UTC, MarkFCain approved these changes

2022-06-17 10:46 UTC, merged