CSP-54-inner-TrainingVenueDetails
SkillsFundingAgency/das-roatp-api pull request #65
Opened 2022-07-27 16:48 UTC by raviudari01

2022-07-28 08:41 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationDetailsQueryValidatorTests.cs
> +        }
Can you add a happy path test here too?

2022-07-28 08:46 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application/ProviderCourse/Queries/GetProviderCourse/GetProviderCourseQueryValidator.cs
> +    }
I can't see any tests for this

2022-07-28 08:46 UTC, MarkFCain reviewed
Some comments to address

2022-07-28 11:08 UTC, MarkFCain approved these changes

2022-08-02 15:42 UTC, DevenKShah requested changes

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/Locations/Queries/GetProviderLocations/GetProviderLocationsQuery.cs
> +        public GetProviderLocationsQuery() { }
What is the purpose of empty validator?

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationDetailsQueryHandlerTests.cs
> +            Assert.ThrowsAsync <NullReferenceException> (() => sut.Handle(query, cancellationToken));
You are not throwing as exception in the handler, so this test is not making sense. We are validating that the location exists. So no need for this test at all.

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application/Locations/Queries/GetProviderLocations/GetProviderLocationsQueryValidator.cs
>                  .Cascade(CascadeMode.Stop)
Should have used Include here while you were changing it

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationsQueryValidatorTests.cs
> +        public async Task ValidateUkprn_InValid_ReturnsError()
Should we not have other tests here?

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationDetailsQueryValidatorTests.cs
> +            var sut = new GetProviderLocationDetailsQueryValidator(Mock.Of<IProviderReadRepository>(), Mock.Of<IProviderLocationsReadRepository>());
This is loose test, there is no expectation set. All the expectations should be set explicitly. If the expectation is that the repository returns null on certain method then that should be set explicitly and we should verify the method was called. Otherwise I can make breaking changes to the repository and this test will still pass. This comment is applied to many tests in this PR. Please correct all the tests that are 🎏

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationDetailsQueryValidatorTests.cs
> +            var sut = new GetProviderLocationDetailsQueryValidator(Mock.Of<IProviderReadRepository>(), Mock.Of<IProviderLocationsReadRepository>());
🎏

2022-08-02 15:42 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/Locations/Queries/ProviderLocations/GetProviderLocationsQueryValidatorTests.cs
> +            var sut = new GetProviderLocationsQueryValidator(Mock.Of<IProviderReadRepository>());
🎏

2022-08-03 08:36 UTC, DevenKShah approved these changes

2022-08-04 09:20 UTC, MarkFCain approved these changes

2022-08-05 12:26 UTC, merged