CSP-184-inner-AddVenueAndDelivery
SkillsFundingAgency/das-roatp-api pull request #72
Opened 2022-08-12 08:38 UTC by raviudari01

2022-08-15 08:04 UTC, DevenKShah requested changes

2022-08-17 07:33 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandHandlerTests.cs
> +            providerLocation.LocationType = LocationType.Provider;
I think this line can be removed, then the moq will test all 3 types? Try it, see if that works

2022-08-17 07:35 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(100, 123, "user", Guid.NewGuid(), true, true);
turn these magic numbers into meaningful variable names please

2022-08-17 07:36 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, "user", Guid.NewGuid(), true, true);
turn magic numbers into meaningful variable names please

2022-08-17 07:36 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 0, "user", locationNavigationId, true, true);
remove magic numbers (see previous comments)

2022-08-17 07:36 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, userId, Guid.NewGuid(), true, true);
remove magic numbers

2022-08-17 07:37 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, "user", Guid.Empty, true, true);
magic numbers

2022-08-17 07:37 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, "user", Guid.NewGuid(), true, true);
magic numbers

2022-08-17 07:37 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, "user", Guid.NewGuid(), hasDayReleaseDeliveryOption, hasBlockReleaseDeliveryOption);
magic numbers

2022-08-17 07:37 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +            _command = new AddProviderCourseLocationCommand(10012002, 123, "user", Guid.NewGuid(), hasDayReleaseDeliveryOption, hasBlockReleaseDeliveryOption);
magic numbers

2022-08-17 07:41 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +        }
You can also check for the message to match AddProviderCourseLocationCommandValidator.TrainingVenueErrorMessage?  Just a suggestion

2022-08-17 07:43 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidator.cs
> +                .MustAsync(async (command, locationNavigationId, _) =>
I couldn't see a test for empty LocationNavigationId.  If there is one and I missed it, please resolve this comment

2022-08-17 07:44 UTC, MarkFCain reviewed
some comments, mostly in the validator tests.  Logic looks fine otherwise.

2022-08-17 08:09 UTC, DevenKShah approved these changes

2022-08-17 08:09 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Application.UnitTests/ProviderCourseLocations/Commands/AddProviderCourseLocation/AddProviderCourseLocationCommandValidatorTests.cs
> +        [TestCase(null, null)]
I don't know how this could have worked, the parameters to the test are not nullable so they must be defaulting to false. Think you need parameters to be nullable?

2022-08-17 08:12 UTC, MarkFCain approved these changes

2022-08-18 12:21 UTC, merged