CSP-256-NAR-Import-job
SkillsFundingAgency/das-roatp-api pull request #84
Opened 2022-09-27 16:24 UTC by raviudari01

2022-09-28 10:34 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Data/Configuration/NationalAchievementRateConfiguration.cs
> +            builder.Property(x => x.Ukprn).HasColumnName("Ukprn").HasColumnType("int");
Ukrpn should be required?

2022-09-28 15:58 UTC, DevenKShah requested changes

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/NationalAchievementRate.sql
> +	[Id] BIGINT PRIMARY KEY IDENTITY (1,1),
Add primary key explicitly with a name

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/NationalAchievementRateOverall.sql
> +	[Id] BIGINT PRIMARY KEY IDENTITY (1,1),
Explicit primary key declaration please

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/NationalAchievementRateOverall_Import.sql
> +	[Id] BIGINT PRIMARY KEY IDENTITY (1,1),
Explicit primary key declaration please

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/NationalAchievementRate_Import.sql
> +	[Id] BIGINT PRIMARY KEY IDENTITY (1,1),
Explicit primary key declaration please

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain.UnitTests/Entities/NationalAchievementRateOverall_ImportTests.cs
> +            var destination = (NationalAchievementRateOverall_Import)source;
add space between arrange, act and assert

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain.UnitTests/Entities/NationalAchievementRate_ImportTests.cs
> +            var destination = (NationalAchievementRate_Import)source;
add space between arrange, act and assert

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Entities/NationalAchievementRateOverall_Import.cs
> +    public class NationalAchievementRateOverall_Import
Do we need _ in the name? Don't see why this cannot follow normal naming convention

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Entities/NationalAchievementRate_Import.cs
> +    public class NationalAchievementRate_Import
Do we need _ in the name? Don't see why this cannot follow normal naming convention

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Models/NationalAchievementRatesOverallApiImport.cs
> +        public string ApprenticeshipLevel { get; set; }
This should be enum type, allow serialiser to do the conversion.

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Models/NationalAchievementRatesOverallApiImport.cs
> +        public string Age { get; set; }
This should be enum type, allow serialiser to do the conversion.

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Extensions/EnumExtensions.cs
> +        public static int ToAge(this string value)
Why are we converting in outer and in the inner. We should be doing this only in outer.

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Models/NationalAchievementRatesApiImport.cs
> +        public string Age { get; set; }
Age and level should be of enum type

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Jobs/Services/ReloadNationalAcheivementRatesService.cs
> +            await _nationalAchievementRatesImportWriteRepository.InsertMany(nationalAchievementRatesLookup.NationalAchievementRates.Select(c => (NationalAchievementRate_Import)c).ToList());
DeleteAll and InsertAll in to table should be done within a transaction, otherwise we will end up in situations where there is no data in the table.

2022-09-28 15:58 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Jobs/Services/ReloadNationalAcheivementRatesService.cs
> +            {
Also we should break this down into two services as there are two different import processes going on. One process should not fail the other.

2022-09-29 14:28 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Entities/NationalAchievementRateOverallImport.cs
> +        public int Age { get; set; }
The entities can have enum types as well so there is no conversion from api model to entity

2022-09-29 14:28 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Domain/Models/NationalAchievementRatesApiImport.cs
> +    public class NationalAchievementRatesApiImport
ApiModel sounds better than ApiImport

2022-09-29 14:28 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Jobs/Services/ReloadNationalAcheivementRatesOverallService.cs
> +            var timeStarted = DateTime.UtcNow;
Put each of the statement in a try block. In the catch, log the exception and return. This will tell us exactly where the error occurred and allow the other import to carry on. Same applies to the other service.

2022-09-29 17:48 UTC, DevenKShah approved these changes

2022-09-29 18:00 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Database/Tables/NationalAchievementRateOverall.sql
> +CREATE NONCLUSTERED INDEX [IDX_NationalAchievementRateOverall_Sector] ON [dbo].[NationalAchievementRateOverall] (SectorSubjectArea, Age, ApprenticeshipLevel)
IDX_NationalAchievementRateOverall_Sector_Age_Level

2022-10-03 07:19 UTC, MarkFCain approved these changes

2022-10-04 14:22 UTC, merged