CSP-329-web-not-retrieving-standards
SkillsFundingAgency/das-roatp-api pull request #96
Opened 2022-10-20 15:46 UTC by raviudari01

2022-10-21 14:13 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Application/Providers/Queries/GetProviders/ProviderAddressModel.cs
> +
remove spaces

2022-10-21 14:16 UTC, MarkFCain approved these changes

2022-10-21 14:16 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Data/Repositories/ProvidersReadRepository.cs
> +                _logger.LogError("Error occured while getting provider {ukprn} error message : {error}", ukprn, e.Message);
I'd change this to _logger.LogError(e,$"Error occured while getting provider {ukprn}")

It makes all parts of the error available in the log

2022-10-21 14:16 UTC, MarkFCain commented on src/SFA.DAS.Roatp.Data/Repositories/ProvidersReadRepository.cs
> +                _logger.LogError("Error occured while getting all providers error message : {error}", e.Message);
see previous suggestion about logging errors

2022-10-24 07:52 UTC, DevenKShah requested changes

2022-10-24 07:52 UTC, DevenKShah commented on src/SFA.DAS.Roatp.Data/Repositories/ProvidersWriteRepository.cs
> +        public async Task<List<Provider>> GetAllProviders()
I don't think this is required as we are mapping ProviderId before saving the address. Remove this method from write repository and use read repository instead.

2022-10-24 10:51 UTC, DevenKShah approved these changes

2022-10-26 10:15 UTC, merged